version: "3.7"

services:
  nanoservice:
    build: .
    container_name: nanoservice
    ports:
      - 5000:5000
    environment:
      - 'NANO_MESSAGE=Nanoservice [compose]'
    networks:
      - nanoservice

  next-nanoservice:
    build: .
    container_name: next-nanoservice
    environment:
      - 'NANO_MESSAGE=Next nanoservice [compose]'
    networks:
      - nanoservice

  sidecar:
    build:
      context: .
      dockerfile: Dockerfile.sidecar
    container_name: sidecar
    ports:
      - 5050:5050
    networks:
      - nanoservice

networks:
  nanoservice:
    name: nanoservice-network