FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /publish
COPY . .
RUN dotnet publish src/Sidecar -c release -o out

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
WORKDIR /app
COPY --from=build /publish/out .
ENV ASPNETCORE_ENVIRONMENT kubernetes
ENV ASPNETCORE_URLS http://*:5050
ENTRYPOINT dotnet Sidecar.dll